version: '3.8'
services:
  backend:
    build: ./BACKEND
    env_file:
      - ./BACKEND/.env
    ports:
      - "4000:4000"
    restart: unless-stopped
    depends_on:
      - mongo
  frontend:
    build: ./FRONTEND
    env_file:
      - ./FRONTEND/.env
    ports:
      - "3000:80"
    restart: unless-stopped
    depends_on:
      - backend
  mongo:
    image: mongo:6
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
volumes:
  mongo_data:
